[package]
name = "radix-leptos-use-size"
description = "Leptos port of Radix Use Size."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos-node-ref.workspace = true
send_wrapper.workspace = true
web-sys = { workspace = true }
radix-observe.workspace = true
