[package]
name = "radix-leptos-menu"
description = "Leptos port of Radix Menu."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
radix-leptos-compose-refs = { path = "../compose-refs", version = "0.0.1" }
radix-leptos-direction = { path = "../direction", version = "0.0.1" }
radix-leptos-dismissable-layer = { path = "../dismissable-layer", version = "0.0.1" }
radix-leptos-focus-guards = { path = "../focus-guards", version = "0.0.1" }
radix-leptos-focus-scope = { path = "../focus-scope", version = "0.0.1" }
radix-leptos-popper = { path = "../popper", version = "0.0.1" }
radix-leptos-primitive = { path = "../primitive", version = "0.0.1" }
