[package]
name = "radix-leptos-focus-scope"
description = "Leptos port of Radix Focus Scope."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
log.workspace = true
once_cell = "1.19.0"
radix-leptos-primitive = { path = "../primitive", version = "0.0.1" }
web-sys = { workspace = true, features = [
    "CustomEvent",
    "CustomEventInit",
    "MutationObserver",
    "MutationObserverInit",
    "MutationRecord",
    "NodeFilter",
] }
