[package]
name = "radix-leptos-portal"
description = "Leptos port of Radix Portal."
homepage = "https://radix.rustforweb.org/primitives/utilities/portal.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
cfg-if = "1.0.0"
leptos.workspace = true
leptos_dom.workspace = true
leptos-node-ref.workspace = true
radix-leptos-primitive.workspace = true
send_wrapper.workspace = true
web-sys.workspace = true

# [features]
# csr = ["leptos_dom/csr"]
# hydrate = ["leptos_dom/hydrate"]
# ssr = ["leptos_dom/ssr"]

# [package.metadata.cargo-all-features]
# skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["ssr", "hydrate"]]
