[package]
name = "radix-leptos-popper"
description = "Leptos port of Radix Popper."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
floating-ui-leptos = "0.0.9"
leptos.workspace = true
radix-leptos-arrow = { path = "../arrow", version = "0.0.1" }
radix-leptos-use-size = { path = "../use-size", version = "0.0.1" }
serde = "1.0.198"
serde_json = "1.0.116"
