[package]
name = "radix-yew-primitive"
description = "Yew port of Radix Primitive."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
radix-yew-slot = { path = "../slot", version = "0.0.2" }
yew.workspace = true
yew-attrs.workspace = true
