[package]
name = "radix-leptos-icons"
description = "Leptos port of Radix Icons."
homepage = "https://radix.rustforweb.org/icons/index.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true

[features]
default = []
accessibility = []
activity-log = []
align-baseline = []
align-bottom = []
align-center-horizontally = []
align-center-vertically = []
align-left = []
align-right = []
align-top = []
all-sides = []
angle = []
archive = []
arrow-bottom-left = []
arrow-bottom-right = []
arrow-down = []
arrow-left = []
arrow-right = []
arrow-top-left = []
arrow-top-right = []
arrow-up = []
aspect-ratio = []
avatar = []
backpack = []
badge = []
bar-chart = []
bell = []
blending-mode = []
bookmark-filled = []
bookmark = []
border-all = []
border-bottom = []
border-dashed = []
border-dotted = []
border-left = []
border-none = []
border-right = []
border-solid = []
border-split = []
border-style = []
border-top = []
border-width = []
box-model = []
box = []
button = []
calendar = []
camera = []
card-stack-minus = []
card-stack-plus = []
card-stack = []
caret-down = []
caret-left = []
caret-right = []
caret-sort = []
caret-up = []
chat-bubble = []
check-circled = []
check = []
checkbox = []
chevron-down = []
chevron-left = []
chevron-right = []
chevron-up = []
circle-backslash = []
circle = []
clipboard-copy = []
clipboard = []
clock = []
code = []
codesandbox-logo = []
color-wheel = []
column-spacing = []
columns = []
commit = []
component-1 = []
component-2 = []
component-boolean = []
component-instance = []
component-none = []
component-placeholder = []
container = []
cookie = []
copy = []
corner-bottom-left = []
corner-bottom-right = []
corner-top-left = []
corner-top-right = []
corners = []
countdown-timer = []
counter-clockwise-clock = []
crop = []
cross-1 = []
cross-2 = []
cross-circled = []
crosshair-1 = []
crosshair-2 = []
crumpled-paper = []
cube = []
cursor-arrow = []
cursor-text = []
dash = []
dashboard = []
desktop = []
dimensions = []
disc = []
discord-logo = []
divider-horizontal = []
divider-vertical = []
dot-filled = []
dot = []
dots-horizontal = []
dots-vertical = []
double-arrow-down = []
double-arrow-left = []
double-arrow-right = []
double-arrow-up = []
download = []
drag-handle-dots-1 = []
drag-handle-dots-2 = []
drag-handle-horizontal = []
drag-handle-vertical = []
drawing-pin-filled = []
drawing-pin = []
dropdown-menu = []
enter-full-screen = []
enter = []
envelope-closed = []
envelope-open = []
eraser = []
exclamation-triangle = []
exit-full-screen = []
exit = []
external-link = []
eye-closed = []
eye-none = []
eye-open = []
face = []
figma-logo = []
file-minus = []
file-plus = []
file-text = []
file = []
font-bold = []
font-family = []
font-italic = []
font-roman = []
font-size = []
font-style = []
frame = []
framer-logo = []
gear = []
github-logo = []
globe = []
grid = []
group = []
half-1 = []
half-2 = []
hamburger-menu = []
hand = []
heading = []
heart-filled = []
heart = []
height = []
hobby-knife = []
home = []
iconjar-logo = []
id-card = []
image = []
info-circled = []
input = []
instagram-logo = []
keyboard = []
lap-timer = []
laptop = []
layers = []
layout = []
letter-case-capitalize = []
letter-case-lowercase = []
letter-case-toggle = []
letter-case-uppercase = []
letter-spacing = []
lightning-bolt = []
line-height = []
link-1 = []
link-2 = []
link-break-1 = []
link-break-2 = []
link-none-1 = []
link-none-2 = []
linkedin-logo = []
list-bullet = []
lock-closed = []
lock-open-1 = []
lock-open-2 = []
loop = []
magic-wand = []
magnifying-glass = []
margin = []
mask-off = []
mask-on = []
minus-circled = []
minus = []
mix = []
mixer-horizontal = []
mixer-vertical = []
mobile = []
modulz-logo = []
moon = []
move = []
notion-logo = []
opacity = []
open-in-new-window = []
overline = []
padding = []
paper-plane = []
pause = []
pencil-1 = []
pencil-2 = []
person = []
pie-chart = []
pilcrow = []
pin-bottom = []
pin-left = []
pin-right = []
pin-top = []
play = []
plus-circled = []
plus = []
question-mark-circled = []
question-mark = []
quote = []
radiobutton = []
reader = []
reload = []
reset = []
resume = []
rocket = []
rotate-counter-clockwise = []
row-spacing = []
rows = []
ruler-horizontal = []
ruler-square = []
scissors = []
section = []
sewing-pin-filled = []
sewing-pin = []
shadow-inner = []
shadow-none = []
shadow-outer = []
shadow = []
share-1 = []
share-2 = []
shuffle = []
size = []
sketch-logo = []
slash = []
slider = []
space-between-horizontally = []
space-between-vertically = []
space-evenly-horizontally = []
space-evenly-vertically = []
speaker-loud = []
speaker-moderate = []
speaker-off = []
speaker-quiet = []
square = []
stack = []
star-filled = []
star = []
stitches-logo = []
stop = []
stopwatch = []
stretch-horizontally = []
stretch-vertically = []
strikethrough = []
sun = []
switch = []
symbol = []
table = []
target = []
text-align-bottom = []
text-align-center = []
text-align-justify = []
text-align-left = []
text-align-middle = []
text-align-right = []
text-align-top = []
text-none = []
text = []
thick-arrow-down = []
thick-arrow-left = []
thick-arrow-right = []
thick-arrow-up = []
timer = []
tokens = []
track-next = []
track-previous = []
transform = []
transparency-grid = []
trash = []
triangle-down = []
triangle-left = []
triangle-right = []
triangle-up = []
twitter-logo = []
underline = []
update = []
upload = []
value-none = []
value = []
vercel-logo = []
video = []
view-grid = []
view-horizontal = []
view-none = []
view-vertical = []
width = []
zoom-in = []
zoom-out = []
full = [
    "accessibility",
    "activity-log",
    "align-baseline",
    "align-bottom",
    "align-center-horizontally",
    "align-center-vertically",
    "align-left",
    "align-right",
    "align-top",
    "all-sides",
    "angle",
    "archive",
    "arrow-bottom-left",
    "arrow-bottom-right",
    "arrow-down",
    "arrow-left",
    "arrow-right",
    "arrow-top-left",
    "arrow-top-right",
    "arrow-up",
    "aspect-ratio",
    "avatar",
    "backpack",
    "badge",
    "bar-chart",
    "bell",
    "blending-mode",
    "bookmark-filled",
    "bookmark",
    "border-all",
    "border-bottom",
    "border-dashed",
    "border-dotted",
    "border-left",
    "border-none",
    "border-right",
    "border-solid",
    "border-split",
    "border-style",
    "border-top",
    "border-width",
    "box-model",
    "box",
    "button",
    "calendar",
    "camera",
    "card-stack-minus",
    "card-stack-plus",
    "card-stack",
    "caret-down",
    "caret-left",
    "caret-right",
    "caret-sort",
    "caret-up",
    "chat-bubble",
    "check-circled",
    "check",
    "checkbox",
    "chevron-down",
    "chevron-left",
    "chevron-right",
    "chevron-up",
    "circle-backslash",
    "circle",
    "clipboard-copy",
    "clipboard",
    "clock",
    "code",
    "codesandbox-logo",
    "color-wheel",
    "column-spacing",
    "columns",
    "commit",
    "component-1",
    "component-2",
    "component-boolean",
    "component-instance",
    "component-none",
    "component-placeholder",
    "container",
    "cookie",
    "copy",
    "corner-bottom-left",
    "corner-bottom-right",
    "corner-top-left",
    "corner-top-right",
    "corners",
    "countdown-timer",
    "counter-clockwise-clock",
    "crop",
    "cross-1",
    "cross-2",
    "cross-circled",
    "crosshair-1",
    "crosshair-2",
    "crumpled-paper",
    "cube",
    "cursor-arrow",
    "cursor-text",
    "dash",
    "dashboard",
    "desktop",
    "dimensions",
    "disc",
    "discord-logo",
    "divider-horizontal",
    "divider-vertical",
    "dot-filled",
    "dot",
    "dots-horizontal",
    "dots-vertical",
    "double-arrow-down",
    "double-arrow-left",
    "double-arrow-right",
    "double-arrow-up",
    "download",
    "drag-handle-dots-1",
    "drag-handle-dots-2",
    "drag-handle-horizontal",
    "drag-handle-vertical",
    "drawing-pin-filled",
    "drawing-pin",
    "dropdown-menu",
    "enter-full-screen",
    "enter",
    "envelope-closed",
    "envelope-open",
    "eraser",
    "exclamation-triangle",
    "exit-full-screen",
    "exit",
    "external-link",
    "eye-closed",
    "eye-none",
    "eye-open",
    "face",
    "figma-logo",
    "file-minus",
    "file-plus",
    "file-text",
    "file",
    "font-bold",
    "font-family",
    "font-italic",
    "font-roman",
    "font-size",
    "font-style",
    "frame",
    "framer-logo",
    "gear",
    "github-logo",
    "globe",
    "grid",
    "group",
    "half-1",
    "half-2",
    "hamburger-menu",
    "hand",
    "heading",
    "heart-filled",
    "heart",
    "height",
    "hobby-knife",
    "home",
    "iconjar-logo",
    "id-card",
    "image",
    "info-circled",
    "input",
    "instagram-logo",
    "keyboard",
    "lap-timer",
    "laptop",
    "layers",
    "layout",
    "letter-case-capitalize",
    "letter-case-lowercase",
    "letter-case-toggle",
    "letter-case-uppercase",
    "letter-spacing",
    "lightning-bolt",
    "line-height",
    "link-1",
    "link-2",
    "link-break-1",
    "link-break-2",
    "link-none-1",
    "link-none-2",
    "linkedin-logo",
    "list-bullet",
    "lock-closed",
    "lock-open-1",
    "lock-open-2",
    "loop",
    "magic-wand",
    "magnifying-glass",
    "margin",
    "mask-off",
    "mask-on",
    "minus-circled",
    "minus",
    "mix",
    "mixer-horizontal",
    "mixer-vertical",
    "mobile",
    "modulz-logo",
    "moon",
    "move",
    "notion-logo",
    "opacity",
    "open-in-new-window",
    "overline",
    "padding",
    "paper-plane",
    "pause",
    "pencil-1",
    "pencil-2",
    "person",
    "pie-chart",
    "pilcrow",
    "pin-bottom",
    "pin-left",
    "pin-right",
    "pin-top",
    "play",
    "plus-circled",
    "plus",
    "question-mark-circled",
    "question-mark",
    "quote",
    "radiobutton",
    "reader",
    "reload",
    "reset",
    "resume",
    "rocket",
    "rotate-counter-clockwise",
    "row-spacing",
    "rows",
    "ruler-horizontal",
    "ruler-square",
    "scissors",
    "section",
    "sewing-pin-filled",
    "sewing-pin",
    "shadow-inner",
    "shadow-none",
    "shadow-outer",
    "shadow",
    "share-1",
    "share-2",
    "shuffle",
    "size",
    "sketch-logo",
    "slash",
    "slider",
    "space-between-horizontally",
    "space-between-vertically",
    "space-evenly-horizontally",
    "space-evenly-vertically",
    "speaker-loud",
    "speaker-moderate",
    "speaker-off",
    "speaker-quiet",
    "square",
    "stack",
    "star-filled",
    "star",
    "stitches-logo",
    "stop",
    "stopwatch",
    "stretch-horizontally",
    "stretch-vertically",
    "strikethrough",
    "sun",
    "switch",
    "symbol",
    "table",
    "target",
    "text-align-bottom",
    "text-align-center",
    "text-align-justify",
    "text-align-left",
    "text-align-middle",
    "text-align-right",
    "text-align-top",
    "text-none",
    "text",
    "thick-arrow-down",
    "thick-arrow-left",
    "thick-arrow-right",
    "thick-arrow-up",
    "timer",
    "tokens",
    "track-next",
    "track-previous",
    "transform",
    "transparency-grid",
    "trash",
    "triangle-down",
    "triangle-left",
    "triangle-right",
    "triangle-up",
    "twitter-logo",
    "underline",
    "update",
    "upload",
    "value-none",
    "value",
    "vercel-logo",
    "video",
    "view-grid",
    "view-horizontal",
    "view-none",
    "view-vertical",
    "width",
    "zoom-in",
    "zoom-out",
]
