[package]
name = "radix-yew-popper"
description = "Yew port of Radix Popper."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
floating-ui-yew = "0.1.2"
radix-yew-arrow = { path = "../arrow", version = "0.0.2" }
radix-yew-primitive = { path = "../primitive", version = "0.0.2" }
radix-yew-use-size = { path = "../use-size", version = "0.0.2" }
serde.workspace = true
serde_json.workspace = true
web-sys.workspace = true
yew.workspace = true
yew-struct-component.workspace = true
