[package]
name = "radix-leptos-slot"
description = "Leptos port of Radix Slot."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
log.workspace = true
radix-leptos-compose-refs = { path = "../compose-refs", version = "0.0.1" }
