[package]
name = "radix-yew-themes"
description = "Yew port of Radix Themes."
homepage = "https://radix.rustforweb.org/themes/index.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
yew.workspace = true
yew-attrs.workspace = true
