[package]
name = "radix-leptos-accessible-icon"
description = "Leptos port of Radix Accessible Icon."
homepage = "https://radix.rustforweb.org/primitives/utilities/accessible-icon.html"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
radix-leptos-visually-hidden.workspace = true