[package]
name = "radix-leptos-arrow"
description = "Leptos port of Radix Arrow."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
radix-leptos-primitive = { path = "../primitive", version = "0.0.1" }
