[package]
name = "radix-leptos-arrow"
description = "Leptos port of Radix Arrow."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos-node-ref.workspace = true
leptos-typed-fallback-show.workspace = true
radix-leptos-primitive.workspace = true
