[package]
name = "radix-leptos-use-escape-keydown"
description = "Leptos port of Radix Use Escape Key Down."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
web-sys = { workspace = true, features = ["EventListenerOptions"] }
